/** Launch the payer's native banking app from a settlement transfer.
 *
 * We navigate to the app's own launch target — `tcb://` on iOS, an
 * `intent://…;package=…;end` URL on Android — taken from `bank-apps.json`
 * (regenerated by `scripts/gen-bank-apps.py`, which scrapes them; see that
 * script for how and why).
 *
 * ## Two schemes, and why we use the bank's own
 *
 * VietQR documents a payment scheme that looks like the answer to everything:
 *
 *     vietqr://pay?ba=<account>@<bank>&am=<amount>&tn=<note>&bn=…&app=…&url=…
 *
 * **It does not work on a normal phone, and we do not use it.** Tried on an
 * iPhone with Techcombank Mobile installed, `vietqr://pay?…` produced "Safari
 * cannot open the page because the address is invalid" — nothing on the device
 * registers the `vietqr` scheme. It needs a VietQR-aware handler that the bank
 * apps do not provide; the documentation is written for merchants whose
 * customers have one. Do not reintroduce it without testing on a device first.
 *
 * What *is* registered is each bank's own scheme — `tcb://`, `hydro://`,
 * `vietcombankmobile://` — which is why VietQR's own redirector navigates to
 * exactly those. So that is what we launch. It opens the app directly, with no
 * page in between, and carries nothing: see below.
 *
 * ## Why not `dl.vietqr.io/pay`
 *
 * We used to point these same parameters at VietQR's HTTPS redirector, which
 * We used to route through VietQR's HTTPS redirector, which is a visible
 * interstitial that reaches the same place we now reach directly. It also
 * forwards **none** of what it is given: on iOS it serves a page whose script
 * runs `location.href = '<bare scheme>://'`, on Android it 301s to a bare
 * `intent://…;package=…;end`, and the parameters appear nowhere in its response
 * at all — checked across all 37 apps on both platforms, including the four
 * upstream marks `autofill`.
 *
 * ## So the launch cannot pre-fill anything, by any route we have
 *
 * A bank scheme takes no payload, and the one scheme that documents a payload is
 * unhandled. The transfer details only ever travel inside the **QR payload** —
 * NAPAS "Quy định Định dạng mã VietQR" v1.0, ID 54 for the amount, ID 62-08 for
 * the description — which reaches the app by being *read*, not by being linked
 * to. Hence the copy chips beside the button: they are the fastest path that
 * actually exists today.
 *
 * ## On the upstream `autofill` flag
 *
 * The snapshot records `autofill` per app and nothing reads it. Upstream marks
 * 4 of 37 apps as autofill-capable, which describes VietQR's own server-side
 * partner integration (note `bidv.smartbanking.partner://` and the session
 * cookie their page sets) — not anything reachable from a link we build. It is
 * kept in the snapshot for provenance and is not a capability we can use.
 */
import snapshot from "./bank-apps.json";

/** localStorage key holding the app the member last chose to pay from. */
const PREF_KEY = "chiatienan.bankApp";

export interface BankApp {
  appId: string;
  appName: string;
  bankName: string;
  monthlyInstall: number;
  autofill: boolean;
  android: boolean;
  ios: boolean;
  logoAndroid: string | null;
  logoIos: string | null;
  /** `tcb://` — what iOS opens. Null if the scrape found none. */
  schemeIos: string | null;
  /** App Store page, for a phone without this app installed. */
  storeIos: string | null;
  /** `intent://…#Intent;scheme=…;package=…;end` — what Android opens. */
  intentAndroid: string | null;
  /** Android package id: aims the intent at this app, and builds its Play Store
   * fallback URL. */
  packageAndroid: string | null;
}

export interface BankRow {
  code: string;
  bin: string;
  shortName: string;
  hasApp: boolean;
}

export type Platform = "android" | "ios" | "other";

/** Where the payee's money should land, recovered from a settlement QR URL. */
export interface Payee {
  bankCode: string;
  accountNumber: string;
  accountName: string;
}

export const APPS: BankApp[] = snapshot.apps as BankApp[];
export const BANKS: BankRow[] = snapshot.banks as BankRow[];

const APPS_BY_ID = new Map(APPS.map((a) => [a.appId, a]));

/** Apps a member can pick from, most-installed first. */
export function listApps(platform: Platform): BankApp[] {
  const usable = APPS.filter((a) =>
    platform === "ios" ? a.ios : platform === "android" ? a.android : true,
  );
  return [...usable].sort(
    (x, y) => y.monthlyInstall - x.monthlyInstall || x.appName.localeCompare(y.appName),
  );
}

export function appById(appId: string | null | undefined): BankApp | null {
  return appId ? APPS_BY_ID.get(appId) ?? null : null;
}

/** The logo URL for this platform, falling back to the other store's art. */
export function logoFor(app: BankApp, platform: Platform): string | null {
  return platform === "ios"
    ? app.logoIos ?? app.logoAndroid
    : app.logoAndroid ?? app.logoIos;
}

/** Resolve whatever a member typed into `bank_code` to a canonical bank code.
 *
 * The profile field is free text — people type `VCB`, `970436`, or
 * `Vietcombank`. `img.vietqr.io` is forgiving about that; the deeplink is not,
 * so match on code, BIN and short name before giving up.
 */
export function normalizeBankCode(raw: string | null | undefined): string | null {
  const s = (raw ?? "").trim().toLowerCase();
  if (!s) return null;
  const hit =
    BANKS.find((b) => b.code.toLowerCase() === s) ??
    BANKS.find((b) => b.bin === s) ??
    BANKS.find((b) => b.shortName.toLowerCase() === s);
  return hit ? hit.code : null;
}

/** The bank app matching a payee's bank, if one exists.
 *
 * Note this is the *payee's* bank, used only as the opening guess for which app
 * the payer will reach for — people overwhelmingly pay from the app they bank
 * with, and their own is the better guess when we know it.
 */
export function appForBankCode(raw: string | null | undefined): BankApp | null {
  const code = normalizeBankCode(raw);
  return code ? APPS_BY_ID.get(code.toLowerCase()) ?? null : null;
}

/** Recover the payee from a settlement QR URL.
 *
 * Mirrors the URL that `backend/app/qr.py` builds:
 *
 *     {base}/{bank_code}-{account_number}-{template}.png
 *         ?amount=&addInfo=&accountName=
 *
 * Reading it back beats threading new fields through the attachment payload:
 * every settlement already in the thread keeps working, with no migration and
 * no second code path for old messages.
 */
export function parseQrUrl(qrUrl: string | null | undefined): Payee | null {
  if (!qrUrl) return null;
  let url: URL;
  try {
    url = new URL(qrUrl);
  } catch {
    return null;
  }
  const file = url.pathname.split("/").pop() ?? "";
  const stem = file.replace(/\.png$/i, "");
  const parts = stem.split("-");
  // bank code, account number, template — the account number may itself
  // contain hyphens, so peel the known ends and keep the middle.
  if (parts.length < 3) return null;
  const bankCode = parts.shift()!;
  parts.pop(); // template
  const accountNumber = parts.join("-");
  if (!bankCode || !accountNumber) return null;
  return {
    bankCode,
    accountNumber,
    accountName: url.searchParams.get("accountName") ?? "",
  };
}

/** The store page for this app, to fall back to when nothing is installed. */
export function storeUrlFor(app: BankApp, platform: Platform): string | null {
  if (platform === "android") {
    return app.packageAndroid
      ? `https://play.google.com/store/apps/details?id=${app.packageAndroid}`
      : null;
  }
  return app.storeIos;
}

/** Where to send the browser to open this app, or null if we have no target.
 *
 * Takes no transfer details, because neither scheme accepts any — see above.
 *
 * On Android the scraped `intent://` gets a `browser_fallback_url`, which Chrome
 * follows by itself when the package is absent; `end` must stay the last token
 * or Chrome rejects the whole URL. iOS has no such slot, so the caller pairs
 * this with :func:`storeUrlFor` on a timer.
 */
export function appLaunchUrl(app: BankApp, platform: Platform): string | null {
  if (platform === "android") {
    if (!app.intentAndroid) return null;
    const fallback = storeUrlFor(app, platform);
    if (!fallback) return app.intentAndroid;
    return app.intentAndroid.replace(
      /;end$/,
      `;S.browser_fallback_url=${encodeURIComponent(fallback)};end`,
    );
  }
  if (platform === "ios") return app.schemeIos;
  return null;
}

/** Which mobile platform this is, if any.
 *
 * Desktop gets no button: `dl.vietqr.io` has nothing to hand off to there, and
 * the QR is already the right affordance for a laptop screen.
 */
export function detectPlatform(ua?: string): Platform {
  const s = ua ?? (typeof navigator === "undefined" ? "" : navigator.userAgent);
  if (/android/i.test(s)) return "android";
  // iPadOS 13+ reports a desktop Safari UA; the touch-point count gives it away.
  if (/iphone|ipad|ipod/i.test(s)) return "ios";
  if (
    /macintosh/i.test(s) &&
    typeof navigator !== "undefined" &&
    (navigator as Navigator).maxTouchPoints > 1
  ) {
    return "ios";
  }
  return "other";
}

export function isMobile(platform: Platform): boolean {
  return platform === "android" || platform === "ios";
}

/** The app this member last paid from — a better guess than the payee's bank. */
export function getPreferredAppId(): string | null {
  try {
    return window.localStorage.getItem(PREF_KEY);
  } catch {
    return null;
  }
}

export function setPreferredAppId(appId: string): void {
  try {
    window.localStorage.setItem(PREF_KEY, appId);
  } catch {
    // Private mode / storage disabled — the picker still works, it just will
    // not be remembered.
  }
}
