/** Launch the payer's native banking app from a settlement transfer.
 *
 * We navigate to the app's own launch target — `tcb://` on iOS, an
 * `intent://…;package=…;end` URL on Android — taken from `bank-apps.json`
 * (regenerated by `scripts/gen-bank-apps.py`, which scrapes them; see that
 * script for how and why).
 *
 * ## `vietqr://pay` — the scheme that carries the transfer
 *
 * VietQR documents a custom scheme taking the same parameters as its web
 * redirector:
 *
 *     vietqr://pay?ba=<account>@<bank>&am=<amount>&tn=<note>
 *                 &bn=<account holder>&app=<preferred app>&url=<return url>
 *
 * This is the payment link. `ba` is the payee as `ACCOUNT@BANK_CODE`, `app`
 * names the app the payer would rather use, and `url` is where the bank app
 * returns on success. Being a custom scheme it opens the app directly, with no
 * page in between.
 *
 * ## Why not `dl.vietqr.io/pay`
 *
 * We used to point these same parameters at VietQR's HTTPS redirector, which
 * was both slower and lossy. It is a visible interstitial, and it forwards
 * **none** of what it is given: on iOS it serves a page whose script runs
 * `location.href = '<bare scheme>://'`, on Android it 301s to a bare
 * `intent://…;package=…;end`, and the parameters appear nowhere in the response
 * at all. Checked across all 37 apps on both platforms, including the four
 * upstream marks `autofill`. So the transfer details were being dropped in
 * transit, which is exactly why the app opened on its home screen.
 *
 * The snapshot's store links are still load-bearing — they are where a phone
 * with no `vietqr://` handler gets sent. Its per-app `schemeIos` and
 * `intentAndroid` are recorded for provenance only: they are what the redirector
 * hands over, and keeping them is how the next person can check that claim
 * without re-deriving it.
 *
 * ## On the upstream `autofill` flag
 *
 * The snapshot records `autofill` per app and nothing reads it. Upstream marks
 * 4 of 37 apps as autofill-capable, which describes VietQR's own server-side
 * partner integration (note `bidv.smartbanking.partner://` and the session
 * cookie their page sets) — not anything reachable from a link we build. It is
 * kept in the snapshot for provenance and is not a capability we can use.
 */
import snapshot from "./bank-apps.json";

/** localStorage key holding the app the member last chose to pay from. */
const PREF_KEY = "chiatienan.bankApp";

export interface BankApp {
  appId: string;
  appName: string;
  bankName: string;
  monthlyInstall: number;
  autofill: boolean;
  android: boolean;
  ios: boolean;
  logoAndroid: string | null;
  logoIos: string | null;
  /** `tcb://` — the bare scheme the redirector hands over. Provenance only; we
   * launch `vietqr://pay?…` instead, which actually carries the transfer. */
  schemeIos: string | null;
  /** App Store page, for a phone with no `vietqr://` handler installed. */
  storeIos: string | null;
  /** The redirector's Android target. Provenance only, as `schemeIos`. */
  intentAndroid: string | null;
  /** Android package id: aims the intent at this app, and builds its Play Store
   * fallback URL. */
  packageAndroid: string | null;
}

export interface BankRow {
  code: string;
  bin: string;
  shortName: string;
  hasApp: boolean;
}

export type Platform = "android" | "ios" | "other";

/** Where the payee's money should land, recovered from a settlement QR URL. */
export interface Payee {
  bankCode: string;
  accountNumber: string;
  accountName: string;
}

export const APPS: BankApp[] = snapshot.apps as BankApp[];
export const BANKS: BankRow[] = snapshot.banks as BankRow[];

const APPS_BY_ID = new Map(APPS.map((a) => [a.appId, a]));

/** Apps a member can pick from, most-installed first. */
export function listApps(platform: Platform): BankApp[] {
  const usable = APPS.filter((a) =>
    platform === "ios" ? a.ios : platform === "android" ? a.android : true,
  );
  return [...usable].sort(
    (x, y) => y.monthlyInstall - x.monthlyInstall || x.appName.localeCompare(y.appName),
  );
}

export function appById(appId: string | null | undefined): BankApp | null {
  return appId ? APPS_BY_ID.get(appId) ?? null : null;
}

/** The logo URL for this platform, falling back to the other store's art. */
export function logoFor(app: BankApp, platform: Platform): string | null {
  return platform === "ios"
    ? app.logoIos ?? app.logoAndroid
    : app.logoAndroid ?? app.logoIos;
}

/** Resolve whatever a member typed into `bank_code` to a canonical bank code.
 *
 * The profile field is free text — people type `VCB`, `970436`, or
 * `Vietcombank`. `img.vietqr.io` is forgiving about that; the deeplink is not,
 * so match on code, BIN and short name before giving up.
 */
export function normalizeBankCode(raw: string | null | undefined): string | null {
  const s = (raw ?? "").trim().toLowerCase();
  if (!s) return null;
  const hit =
    BANKS.find((b) => b.code.toLowerCase() === s) ??
    BANKS.find((b) => b.bin === s) ??
    BANKS.find((b) => b.shortName.toLowerCase() === s);
  return hit ? hit.code : null;
}

/** The bank app matching a payee's bank, if one exists.
 *
 * Note this is the *payee's* bank, used only as the opening guess for which app
 * the payer will reach for — people overwhelmingly pay from the app they bank
 * with, and their own is the better guess when we know it.
 */
export function appForBankCode(raw: string | null | undefined): BankApp | null {
  const code = normalizeBankCode(raw);
  return code ? APPS_BY_ID.get(code.toLowerCase()) ?? null : null;
}

/** Recover the payee from a settlement QR URL.
 *
 * Mirrors the URL that `backend/app/qr.py` builds:
 *
 *     {base}/{bank_code}-{account_number}-{template}.png
 *         ?amount=&addInfo=&accountName=
 *
 * Reading it back beats threading new fields through the attachment payload:
 * every settlement already in the thread keeps working, with no migration and
 * no second code path for old messages.
 */
export function parseQrUrl(qrUrl: string | null | undefined): Payee | null {
  if (!qrUrl) return null;
  let url: URL;
  try {
    url = new URL(qrUrl);
  } catch {
    return null;
  }
  const file = url.pathname.split("/").pop() ?? "";
  const stem = file.replace(/\.png$/i, "");
  const parts = stem.split("-");
  // bank code, account number, template — the account number may itself
  // contain hyphens, so peel the known ends and keep the middle.
  if (parts.length < 3) return null;
  const bankCode = parts.shift()!;
  parts.pop(); // template
  const accountNumber = parts.join("-");
  if (!bankCode || !accountNumber) return null;
  return {
    bankCode,
    accountNumber,
    accountName: url.searchParams.get("accountName") ?? "",
  };
}

/** The documented VietQR payment scheme. `pay` is the host, not a path. */
export const VIETQR_SCHEME = "vietqr";
export const VIETQR_PAY_HOST = "pay";

/** The transfer, as the query VietQR's `pay` action expects.
 *
 * Ordered as the documentation lists them, so a URL in a bug report can be
 * diffed against the docs by eye.
 */
export function transferParams(
  payee: Payee,
  amount: number,
  note: string,
  appId?: string | null,
  returnUrl?: string | null,
): string {
  // `ba` is ACCOUNT@BANK_CODE, and the bank is the *payee's*. `app` is the
  // payer's own app. Conflating the two would send money to the wrong bank.
  const bank = (normalizeBankCode(payee.bankCode) ?? payee.bankCode).toLowerCase();
  const params = [
    `ba=${encodeURIComponent(payee.accountNumber)}@${encodeURIComponent(bank)}`,
    `am=${encodeURIComponent(String(Math.round(amount)))}`,
  ];
  if (note) params.push(`tn=${encodeURIComponent(note)}`);
  if (payee.accountName) params.push(`bn=${encodeURIComponent(payee.accountName)}`);
  if (appId) params.push(`app=${encodeURIComponent(appId)}`);
  if (returnUrl) params.push(`url=${encodeURIComponent(returnUrl)}`);
  return params.join("&");
}

/** The store page for this app, to fall back to when nothing is installed. */
export function storeUrlFor(app: BankApp, platform: Platform): string | null {
  if (platform === "android") {
    return app.packageAndroid
      ? `https://play.google.com/store/apps/details?id=${app.packageAndroid}`
      : null;
  }
  return app.storeIos;
}

/** Where to send the browser to pay this transfer, or null off mobile.
 *
 * iOS gets `vietqr://pay?…` and nothing else — the OS has no fallback slot, so
 * the caller pairs this with :func:`storeUrlFor` on a timer.
 *
 * Android gets the same query wrapped in an `intent://`, which buys two things
 * a bare scheme link cannot: `package` aims it at the payer's own bank app when
 * we know it, and `browser_fallback_url` sends them to the Play Store by
 * themselves when that app is absent. `end` must stay the last token or Chrome
 * rejects the whole URL.
 */
export function payLaunchUrl(
  app: BankApp | null,
  platform: Platform,
  payee: Payee,
  amount: number,
  note: string,
  returnUrl?: string | null,
): string | null {
  const query = transferParams(payee, amount, note, app?.appId, returnUrl);
  if (platform === "ios") return `${VIETQR_SCHEME}://${VIETQR_PAY_HOST}?${query}`;
  if (platform !== "android") return null;
  const parts = [`scheme=${VIETQR_SCHEME}`];
  if (app?.packageAndroid) parts.push(`package=${app.packageAndroid}`);
  const store = app ? storeUrlFor(app, platform) : null;
  if (store) parts.push(`S.browser_fallback_url=${encodeURIComponent(store)}`);
  return `intent://${VIETQR_PAY_HOST}?${query}#Intent;${parts.join(";")};end`;
}

/** Which mobile platform this is, if any.
 *
 * Desktop gets no button: `dl.vietqr.io` has nothing to hand off to there, and
 * the QR is already the right affordance for a laptop screen.
 */
export function detectPlatform(ua?: string): Platform {
  const s = ua ?? (typeof navigator === "undefined" ? "" : navigator.userAgent);
  if (/android/i.test(s)) return "android";
  // iPadOS 13+ reports a desktop Safari UA; the touch-point count gives it away.
  if (/iphone|ipad|ipod/i.test(s)) return "ios";
  if (
    /macintosh/i.test(s) &&
    typeof navigator !== "undefined" &&
    (navigator as Navigator).maxTouchPoints > 1
  ) {
    return "ios";
  }
  return "other";
}

export function isMobile(platform: Platform): boolean {
  return platform === "android" || platform === "ios";
}

/** The app this member last paid from — a better guess than the payee's bank. */
export function getPreferredAppId(): string | null {
  try {
    return window.localStorage.getItem(PREF_KEY);
  } catch {
    return null;
  }
}

export function setPreferredAppId(appId: string): void {
  try {
    window.localStorage.setItem(PREF_KEY, appId);
  } catch {
    // Private mode / storage disabled — the picker still works, it just will
    // not be remembered.
  }
}
