/** Launch a native banking app pre-filled with a settlement transfer.
 *
 * VietQR publishes a redirector at `dl.vietqr.io/pay` that hands off to an
 * installed bank app, optionally carrying the payee and amount with it:
 *
 *     https://dl.vietqr.io/pay?app=<appId>&ba=<account>@<bank>&am=<amount>
 *                             &tn=<note>&bn=<account holder>
 *
 * It is an HTTPS universal link rather than a custom scheme, so a member
 * without that app installed lands on VietQR's own fallback page instead of a
 * dead tap. Every parameter is data the QR image already carries to
 * `img.vietqr.io` — this adds no new disclosure.
 *
 * The app list is a committed snapshot (`bank-apps.json`, regenerated by
 * `scripts/gen-bank-apps.py`), not a runtime fetch: a settlement card must not
 * wait on a third party to render its button.
 *
 * ## On the upstream `autofill` flag
 *
 * The snapshot records `autofill` per app, and nothing here reads it. Upstream
 * marks only 4 of 37 apps as autofill-capable, but that is demonstrably stale —
 * TPBank is flagged `false` and pre-fills fine in practice. Gating on it would
 * hide a working button from whoever VietQR has not re-surveyed, and labelling
 * from it would print a warning that the user's own phone contradicts. So the
 * button is offered wherever an app resolves, the label promises only what we
 * know ("open the app"), and the copy actions alongside it cover the case where
 * a given app turns out not to pre-fill after all.
 */
import snapshot from "./bank-apps.json";

export const DEEPLINK_BASE = "https://dl.vietqr.io/pay";

/** localStorage key holding the app the member last chose to pay from. */
const PREF_KEY = "chiatienan.bankApp";

export interface BankApp {
  appId: string;
  appName: string;
  bankName: string;
  monthlyInstall: number;
  autofill: boolean;
  android: boolean;
  ios: boolean;
  logoAndroid: string | null;
  logoIos: string | null;
}

export interface BankRow {
  code: string;
  bin: string;
  shortName: string;
  hasApp: boolean;
}

export type Platform = "android" | "ios" | "other";

/** Where the payee's money should land, recovered from a settlement QR URL. */
export interface Payee {
  bankCode: string;
  accountNumber: string;
  accountName: string;
}

export const APPS: BankApp[] = snapshot.apps as BankApp[];
export const BANKS: BankRow[] = snapshot.banks as BankRow[];

const APPS_BY_ID = new Map(APPS.map((a) => [a.appId, a]));

/** Apps a member can pick from, most-installed first. */
export function listApps(platform: Platform): BankApp[] {
  const usable = APPS.filter((a) =>
    platform === "ios" ? a.ios : platform === "android" ? a.android : true,
  );
  return [...usable].sort(
    (x, y) => y.monthlyInstall - x.monthlyInstall || x.appName.localeCompare(y.appName),
  );
}

export function appById(appId: string | null | undefined): BankApp | null {
  return appId ? APPS_BY_ID.get(appId) ?? null : null;
}

/** The logo URL for this platform, falling back to the other store's art. */
export function logoFor(app: BankApp, platform: Platform): string | null {
  return platform === "ios"
    ? app.logoIos ?? app.logoAndroid
    : app.logoAndroid ?? app.logoIos;
}

/** Resolve whatever a member typed into `bank_code` to a canonical bank code.
 *
 * The profile field is free text — people type `VCB`, `970436`, or
 * `Vietcombank`. `img.vietqr.io` is forgiving about that; the deeplink is not,
 * so match on code, BIN and short name before giving up.
 */
export function normalizeBankCode(raw: string | null | undefined): string | null {
  const s = (raw ?? "").trim().toLowerCase();
  if (!s) return null;
  const hit =
    BANKS.find((b) => b.code.toLowerCase() === s) ??
    BANKS.find((b) => b.bin === s) ??
    BANKS.find((b) => b.shortName.toLowerCase() === s);
  return hit ? hit.code : null;
}

/** The bank app matching a payee's bank, if one exists.
 *
 * Note this is the *payee's* bank, used only as the opening guess for which app
 * the payer will reach for — people overwhelmingly pay from the app they bank
 * with, and their own is the better guess when we know it.
 */
export function appForBankCode(raw: string | null | undefined): BankApp | null {
  const code = normalizeBankCode(raw);
  return code ? APPS_BY_ID.get(code.toLowerCase()) ?? null : null;
}

/** Recover the payee from a settlement QR URL.
 *
 * Mirrors the URL that `backend/app/qr.py` builds:
 *
 *     {base}/{bank_code}-{account_number}-{template}.png
 *         ?amount=&addInfo=&accountName=
 *
 * Reading it back beats threading new fields through the attachment payload:
 * every settlement already in the thread keeps working, with no migration and
 * no second code path for old messages.
 */
export function parseQrUrl(qrUrl: string | null | undefined): Payee | null {
  if (!qrUrl) return null;
  let url: URL;
  try {
    url = new URL(qrUrl);
  } catch {
    return null;
  }
  const file = url.pathname.split("/").pop() ?? "";
  const stem = file.replace(/\.png$/i, "");
  const parts = stem.split("-");
  // bank code, account number, template — the account number may itself
  // contain hyphens, so peel the known ends and keep the middle.
  if (parts.length < 3) return null;
  const bankCode = parts.shift()!;
  parts.pop(); // template
  const accountNumber = parts.join("-");
  if (!bankCode || !accountNumber) return null;
  return {
    bankCode,
    accountNumber,
    accountName: url.searchParams.get("accountName") ?? "",
  };
}

/** Build the `dl.vietqr.io` handoff URL for one transfer. */
export function buildDeeplink(
  appId: string,
  payee: Payee,
  amount: number,
  note: string,
): string {
  // The bank in `ba` is the payee's; `app` is the payer's own app. They are
  // usually different banks and must not be conflated.
  const bank = (normalizeBankCode(payee.bankCode) ?? payee.bankCode).toLowerCase();
  const params = [
    `app=${encodeURIComponent(appId)}`,
    // `@` is a sub-delimiter and legal unencoded in a query value; VietQR's own
    // examples show it raw, so keep it readable rather than %40.
    `ba=${encodeURIComponent(payee.accountNumber)}@${encodeURIComponent(bank)}`,
    `am=${encodeURIComponent(String(Math.round(amount)))}`,
  ];
  if (note) params.push(`tn=${encodeURIComponent(note)}`);
  if (payee.accountName) params.push(`bn=${encodeURIComponent(payee.accountName)}`);
  return `${DEEPLINK_BASE}?${params.join("&")}`;
}

/** Which mobile platform this is, if any.
 *
 * Desktop gets no button: `dl.vietqr.io` has nothing to hand off to there, and
 * the QR is already the right affordance for a laptop screen.
 */
export function detectPlatform(ua?: string): Platform {
  const s = ua ?? (typeof navigator === "undefined" ? "" : navigator.userAgent);
  if (/android/i.test(s)) return "android";
  // iPadOS 13+ reports a desktop Safari UA; the touch-point count gives it away.
  if (/iphone|ipad|ipod/i.test(s)) return "ios";
  if (
    /macintosh/i.test(s) &&
    typeof navigator !== "undefined" &&
    (navigator as Navigator).maxTouchPoints > 1
  ) {
    return "ios";
  }
  return "other";
}

export function isMobile(platform: Platform): boolean {
  return platform === "android" || platform === "ios";
}

/** The app this member last paid from — a better guess than the payee's bank. */
export function getPreferredAppId(): string | null {
  try {
    return window.localStorage.getItem(PREF_KEY);
  } catch {
    return null;
  }
}

export function setPreferredAppId(appId: string): void {
  try {
    window.localStorage.setItem(PREF_KEY, appId);
  } catch {
    // Private mode / storage disabled — the picker still works, it just will
    // not be remembered.
  }
}
